version: '3.4'

networks:
  dashbase_backend:
    external: true

services:
  auth:
    image: dashbase/auth:nightly
    networks:
      - dashbase_backend
    configs:
      - source: auth_config
        target: /app/config.yml
    ports:
      - target: 9678
        published: 9678
        protocol: tcp
        mode: host
    volumes:
      - auth_db:/data/auth:rw
      - logs:/app/logs:rw
    command: ["server", "/app/config.yml"]
    environment:
      JAVA_OPTS: -Xmx512m -Xms256m -XX:NewSize=256m

configs:
  auth_config:
    file: ./config/dashbase-auth/config.yml

volumes:
  auth_db:
  logs:
    external: true
