# This stack needs to be deployed as `dashbase`
# $ docker stack deploy -c docker-stack-base.yml dashbase

version: '3.4'

services:
  # We need at least one service for docker stack deploy to work.
  dummy:
    image: alpine
    deploy:
      replicas: 0
    networks:
      - backend

networks:
  backend:
    driver: overlay
    attachable: true
