version: '3.4'
configs:
  proxy_config:
    file: ./config/proxy/config.yml
  proxy_metricbeat_config:
    file: config/metricbeat/proxy.yml
networks:
  dashbase_backend:
    external: true
services:
  proxy:
    image: dashbase/proxy:nightly
    networks:
      - dashbase_backend
    configs:
      - source: proxy_config
        target: /app/config.yml
    ports:
      - "9200:9200"
    command: ["server", "/app/config.yml"]
    volumes:
      - logs:/app/logs:rw
    environment:
      KAFKA_BROKER_URL: kafka:9092
  proxy_metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.1.2
    configs:
      - source: proxy_metricbeat_config
        target: /usr/share/metricbeat/metricbeat.yml
    networks:
      - dashbase_backend

volumes:
  logs:
    external: true
